version: '3.6'
services:
  iris-ml:
    build:
      context: ./iris
      dockerfile: Dockerfile
    restart: always
    hostname: iris-ml
    ports:
      - 9091:51773
      - 9092:52773
      - 9093:53773

  iris-ml-suite:
    build:
      context: ./app
      dockerfile: Dockerfile
    hostname: python-iris-ml
    restart: always
    depends_on:
      - iris-ml
    links:
      - iris-ml
    ports:
      - 80:8050
    environment:
      WAIT_HOSTS: iris-ml:51773
    command: predict.py